SYSTEM_MAIL_ADDRESS: "no-reply@thanks-gift.cloud"

# 運営会社の情報
OPERATING_COMPANY_EMAIL: 'info@fpec.jp'
OPERATING_COMPANY_NAME: '株式会社FPEC'

# 野田くんの情報
OPERATING_MEMBER_EMAIL: 'noda.homey@gmail.com'
OPERATING_MEMBER_NAME: '野田周生'

# 注文情報
ORDER_DATE: 15

# アプリの使い方URL
THANKS_GIFT_MANUAL_LINK: 'https://sites.google.com/view/thanks-gift/%E3%83%9B%E3%83%BC%E3%83%A0'
