SYSTEM_MAIL_ADDRESS: "no-reply@one-step-gift.com"

# 運営会社の情報
OPERATING_COMPANY_EMAIL: 'info@fpec.jp'
OPERATING_COMPANY_NAME: '株式会社FPEC'

# 野田くんの情報
OPERATING_MEMBER_EMAIL: 'noda.homey@gmail.com'
OPERATING_MEMBER_NAME: '野田周生'

# 注文情報
ORDER_DATE: 15
