SYSTEM_MAIL_ADDRESS: "no-reply@one-step-gift.com"

# 運営会社の情報
OPERATING_COMPANY_EMAIL: 'info@fpec.jp'
OPERATING_COMPANY_NAME: '株式会社FPEC'

# 注文情報
ORDER_DATE: 15

# アプリの使い方URL
THANKS_GIFT_MANUAL_LINK: 'https://sites.google.com/view/thanks-gift/%E3%83%9B%E3%83%BC%E3%83%A0'
