SYSTEM_MAIL_ADDRESS: "no-reply@example.com"

# 運営会社の情報
# NOTE 本番の送信専用に送信する
OPERATING_COMPANY_EMAIL: 'operate_company@example.com'
OPERATING_COMPANY_NAME: '株式会社DEVELOPMENT'

# 野田くんの情報
OPERATING_MEMBER_EMAIL: 'noda.homey@gmail.com'
OPERATING_MEMBER_NAME: '野田周生'

# 注文情報
ORDER_DATE: 16

# アプリの使い方URL
THANKS_GIFT_MANUAL_LINK: 'https://sites.google.com/view/thanks-gift/%E3%83%9B%E3%83%BC%E3%83%A0'
